spring:
  datasource:
    username: xxxx
    password: xxxxx
    #?serverTimezone=UTC解决时区的报错
    url: jdbc:mysql://localhost:3306/easy_eat?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai
  web:
    resources:
      static-locations: classpath:static/,file:/static
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 101MB
server:
  port: 8082

mybatis-plus:
  type-aliases-package: com.easyEat.entity
  configuration:
    call-setters-on-nulls: false
    #开启驼峰
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

  mapper-locations: classpath*:mapper/**/*Mapper.xml
  global-config:
    banner: true
    db-config:
      #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
      id-type: ASSIGN_UUID
      logic-not-delete-value: 1
      logic-delete-value: 0
logging:
  level:
    root: INFO #日志配置DEBUG,INFO,WARN,ERROR